### ISSUE TITLE
Platform Emulator Error, cant open settings and could not be constructed

### ISSUE THREAD

**Issue by nirgranth** [Kyza/BetterDiscordPlugins#4]
![image](https://user-images.githubusercontent.com/48947296/146276428-6db56218-caec-4bed-b443-f0a7553bba4a.png)

**Comment by Nirgranth** [comment]
sry wrong repo

**Comment by SwiftyPop** [comment]
Any update on this? A lot of people do stated the issue in the discord "support" server and people there just replying with memes and jokes..

**Comment by Nirgranth** [comment]
Still the same,
Tell me what to do to get more info
![image](https://user-images.githubusercontent.com/48947296/147808718-80c55a53-0235-4259-aebe-7ad5d2a68f23.png)

**Comment by nirgranth** [comment]
![image](https://user-images.githubusercontent.com/48947296/150884184-f4b088cc-2564-424b-941e-7e00ae042c3a.png)

**Comment by redbluexe1** [comment]
same
